version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - ecommerce_network

#  app:
#    build: .
#    depends_on:
#      - postgres
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/ecommerce
#      SPRING_R2DBC_USERNAME: user
#      SPRING_R2DBC_PASSWORD: password
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#      SPRING_LIQUIBASE_ENABLED: true
#      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/ecommerce
#      SPRING_LIQUIBASE_USER: user
#      SPRING_LIQUIBASE_PASSWORD: password
#      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml
#    ports:
#      - "8080:8080"
#    networks:
#      - ecommerce_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  ecommerce_network:
    driver: bridge